---
- name: Create KinD node registry config
  ansible.builtin.template:
    src: registry-config.toml.j2
    dest: /tmp/registry_config.toml
    mode: "0644"
  register: node_registry_config

- name: Determine KinD nodes
  ansible.builtin.shell: kind get nodes --name {{ kind_cluster_name }}
  register: kind_cluster_nodes
  changed_when: false

- name: Create registry config directory in KinD nodes
  community.docker.docker_container_exec:
    container: "{{ item }}"
    command: mkdir -p /etc/containerd/certs.d
  loop: "{{ kind_cluster_nodes.stdout_lines }}"
  when: node_registry_config.changed

- name: Apply registry config to KinD nodes
  community.docker.docker_container_copy_into:
    container: "{{ item }}"
    path: /tmp/registry_config.toml
    container_path: /etc/containerd/certs.d/localhost:{{ registry_host_port }}
  loop: "{{ kind_cluster_nodes.stdout_lines }}"
