---
- name: Check if registry container exists
  command: docker inspect {{ registry_container_name }}
  register: registry_inspect
  changed_when: false
  failed_when: false

- name: Remove existing registry container
  command: docker rm -f {{ registry_container_name }}
  when: registry_inspect.rc == 0

- name: Run local container registry
  docker_container:
    name: "{{ registry_container_name }}"
    image: "{{ registry_image }}"
    state: started
    restart_policy: always
    ports:
      - "{{ registry_host_port }}:{{ registry_container_port }}"
    volumes:
      - "{{ registry_data_dir }}:/var/lib/registry"
