apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ./grafana/route-hostnames-patch.yaml
    target:
      kind: HTTPRoute
      name: grafana
      namespace: monitoring

generatorOptions:
 disableNameSuffixHash: true

secretGenerator:
  - name: grafana-secrets
    namespace: monitoring
    type: Opaque
    envs:
      - secrets.env
