---
- name: Create KinD cluster config
  register: kind_config
  ansible.builtin.template:
    src: kind-config.yml.j2
    dest: "{{ temp_dir }}/kind-config.yml"
    mode: "0644"
  notify: Delete KinD cluster

- name: Flush handlers for KinD cluster
  ansible.builtin.meta: flush_handlers

- name: Create KinD cluster
  ansible.builtin.shell: >
      kind create cluster
       --name {{ kind_cluster_name }}
       --config {{ temp_dir }}/kind-config.yml
      --kubeconfig ~/.kube/local.config
      --image "kindest/node:{{ kind_kubernetes_version }}"
      --wait 5m
  register: kind_create
  changed_when: kind_create.rc == 0
  failed_when:
    - kind_create.rc != 0
    - "'already exist' not in kind_create.stderr"

- name: Configure kubectl for KinD cluster
  ansible.builtin.shell: kind get kubeconfig --name {{ kind_cluster_name }}
  register: kubeconfig
  changed_when: false

- name: Save kubeconfig
  copy:
    content: "{{ kubeconfig.stdout }}"
    dest: ~/.kube/local.config
    mode: "0600"
