---
- name: Create KinD cluster config
  register: kind_config
  ansible.builtin.template:
    src: kind-config.yml.j2
    dest: "{{ temp_dir }}/kind-config.yml"
    mode: "0644"

- name: Delete KinD cluster
  ansible.builtin.shell: kind delete cluster --name {{ kind_cluster_name }}
  when: kind_config.changed

- name: Create KinD cluster
  ansible.builtin.shell: >
      kind create cluster
      --name {{ kind_cluster_name }}
      --config {{ temp_dir }}/kind-config.yml
      --kubeconfig {{ temp_dir }}/kube.config
      --image "kindest/node:{{ kind_kubernetes_version }}"
      --wait 5m
  environment:
    PATH: "{{ remote_path }}"
  register: kind_create
  changed_when: kind_create.rc == 0
  failed_when:
    - kind_create.rc != 0
    - "'already exist' not in kind_create.stderr"

- name: Configure kubectl for KinD cluster
  ansible.builtin.shell: kind get kubeconfig --name {{ kind_cluster_name }}
  environment:
    PATH: "{{ remote_path }}"
  register: kubeconfig
  changed_when: false

- name: Save kubeconfig
  copy:
    content: "{{ kubeconfig.stdout }}"
    dest: "~/.kube/{{ kind_cluster_name }}.config"
    mode: "0600"
