---
- name: Create KinD cluster config
  template:
    src: kind-config.yml.j2
    dest: /tmp/kind-config.yml
    mode: "0644"

- name: Create KinD cluster
  command: >
    kind create cluster
    --name {{ kind_cluster_name }}
    --config /tmp/kind-config.yml
    --image "kindest/node:{{ kind_kubernetes_version }}"
  register: kind_create
  changed_when: kind_create.rc == 0
  failed_when: "'already exists' not in kind_create.stderr and kind_create.rc != 0"

- name: Configure kubectl for KinD cluster
  command: kind get kubeconfig --name {{ kind_cluster_name }}
  register: kubeconfig
  changed_when: false

- name: Save kubeconfig
  copy:
    content: "{{ kubeconfig.stdout }}"
    dest: ~/.kube/local.config
    mode: "0600"
