---
- name: Deploy microk8s
  hosts: nodes
  roles:
    - role: microk8s
      tasks_from: install
    - role: microk8s
      tasks_from: config

- name: Assemble cluster
  hosts: nodes
  serial: 1
  roles:
    - role: microk8s
      tasks_from: join
