- name: Deploy microk8s
  hosts: nodes
  vars:
    domain: outer-planes.casa
    microk8s_version: 1.34/stable
  tasks:
    - name: Install microk8s instance
      ansible.builtin.include_tasks:
        file: tasks/install.yaml
    - name: Configure microk8s instance
      ansible.builtin.include_tasks:
        file: tasks/config.yaml
- name: Assemble cluster
  hosts: nodes
  serial: 1
  tasks:
    - ansible.builtin.include_tasks:
        file: tasks/join.yaml
