---
- name: Deploy microk8s
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Populate known_hosts on control node
      delegate_to: localhost
      ansible.builtin.shell: |
        ssh-keyscan "{{ inventory_hostname }}" >> ~/.ssh/known_hosts
      changed_when: false
      failed_when: false
    - name: Gather facts from hosts
      ansible.builtin.gather_facts:
  roles:
    - role: microk8s-install
    - role: microk8s-config
    - role: microk8s-join
