- name: Install microk8s
  become: true
  check_mode: true
  register: microk8s_state
  community.general.snap:
    name:
      - microk8s
    channel: "{{ microk8s_version }}"
    classic: true
- name: Install snapd
  become: true
  ansible.builtin.package:
    name: snapd
    state: present
- name: Install microk8s
  become: true
  community.general.snap:
    name:
      - microk8s
    channel: "{{ microk8s_version }}"
    classic: true
