{
 "title": "Cloudflare / Ingress Tunnels",
 "tags": [ "cloudflare" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Edge Connections",
   "type": "stat",
   "gridPos": { "h": 16, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(edge_location) (cloudflared_tunnel_server_locations)",
     "legendFormat": "{{edge_location}}"
    }
   ]
  },
  {
   "title": "QUIC Round Trip Time",
   "type": "stat",
   "gridPos": { "h": 16, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(quic_client_latest_rtt)", "legendFormat": "average" },
    { "expr": "max(quic_client_latest_rtt)", "legendFormat": "maximum" },
    { "expr": "min(quic_client_latest_rtt)", "legendFormat": "minimum" }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(pod) (increase(cloudflared_tunnel_total_requests[1m]))",
     "legendFormat": "{{pod}} total"
    },
    {
     "expr": "sum by(pod) (increase(cloudflared_tunnel_request_errors[1m]))",
     "legendFormat": "{{pod}} errors"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(status_code) (increase(cloudflared_tunnel_response_by_code[1m]))",
     "legendFormat": "{{pod}} {{status_code}}"
    }
   ]
  }
 ]
}