---
- name: Check if kubectl is installed
  ansible.builtin.shell: kubectl version --client
  register: kubectl_check
  changed_when: false

- name: Get kubectl client version
  ansible.builtin.set_fact:
    kubectl_client_version: "{{ kubectl_check.stdout_lines[0] | regex_replace('^Client Version:\\s*v([0-9]+\\.[0-9]+\\.[0-9]+).*', '\\1') if kubectl_check.stdout_lines | default([]) | length > 0 else '' }}"
  when: kubectl_check.rc == 0

- name: Print kubectl client version
  ansible.builtin.debug:
    msg: "Kubectl client version: {{ kubectl_client_version | default('not found') }}"

- name: Fail if kubectl version is too old
  ansible.builtin.fail:
    msg: "Kubectl >= 1.34.0 is required. Found {{ kubectl_client_version | default('not installed') }}."
  when:
        - kubectl_check.rc == 0
        - kubectl_client_version is defined
        - kubectl_client_version is version('1.34.0', '<')
