---
- include_tasks: check-docker.yml
  tags:
    - check-prerequisites
    - check-prerequisites-docker

- include_tasks: check-kind.yml
  tags:
    - check-prerequisites
    - check-prerequisites-kind

- include_tasks: check-kubectl.yml
  tags:
    - check-prerequisites
    - check-prerequisites-kubectl
- include_tasks: check-python.yml
  tags:
    - check-prerequisites
    - check-prerequisites-python
