apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager
spec:
  acme:
    email: admin@outer-planes.net
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-account-key
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: do-creds
              key: ACCESS_TOKEN
