apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      outer-planes.net/deployment: monitoring

resources:
  - ./namespace.yaml
  - ./prometheus/rbac.yaml
  - ./prometheus/configmap.yaml
  - ./prometheus/deployment.yaml
  - ./prometheus/service.yaml
  - ./prometheus/node-exporter.yaml
  - ./grafana/configmap.yaml
  - ./grafana/deployment.yaml
  - ./grafana/service.yaml
