apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: issuer.yaml

generatorOptions:
 disableNameSuffixHash: true


secretGenerator:
  - name: do-creds
    namespace: cert-manager
    type: Opaque
    envs:
      - secrets.env
