apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:
  ports:
    - name: api
      port: 8080
      targetPort: 9090 
  selector: 
    app: prometheus-server
