apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway
  namespace: istio-public-ingress
spec:
  secretName: gateway-cert
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  duration: 2160h
  renewBefore: 720h
  issuerRef:
    kind: ClusterIssuer
    name: cert-manager
